upstream django {
    server web:8000;
}

server {
    listen 80;
    server_name _;

    # Tamanho máximo do upload
    client_max_body_size 20M;

    # Arquivos estáticos servidos direto pelo nginx
    location /static/ {
        alias /app/staticfiles/;
    }

    # Arquivos enviados (volume media_data)
    location /media/ {
        alias /app/media/;
    }

    # Todo o resto vai para o Gunicorn
    location / {
        proxy_pass http://django;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
